# This is a config for E2B sandbox template.
# You can use template ID (d703jrwexgdvrs5u3b7v) or template name (my-vibe) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("my-vibe") # Sync sandbox
# sandbox = await AsyncSandbox.create("my-vibe") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('my-vibe')

team_id = "e893230a-e257-4e65-9f07-c111580c1afc"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "my-vibe"
template_id = "d703jrwexgdvrs5u3b7v"
